// Arquivo com sobrenomes brasileiros
var lastNames = [
    "Fagundes","Bittencourt","Antunes","Torres","Cavalcanti","Queiroz","Assis","Garcia","Peixoto","Siqueira",
    "Bragança","Pacheco","Prado","Amorim","Macedo","Barros","Matos","Fontes","Batista","Ramalho",
    "Chaves","Britto","Arruda","Monte Negro","Passos","Coutinho","Leite","Azevedo","Teles","Sales",
    "Fonseca","Furtado","Cintra","Valentim","Pimentel","Pessanha","Serafim","Tolentino","Sodré","Roriz",
    "Parente","Caldas","Castilho","Mendonça","Dornelles","Camarço","Berbert","Alvarenga","Fagundes","Parga",
    "Fleury","Sodré","Mafra","Travassos","Serrano","Severiano","Magalhães","Curi","Bellini","Sampaio",
    "Mizrahi","Garrido","Schenker","Roriz","Simões","Guasti","Zambrano","Vaz","Paz","Aguiar",
    "Beltrão","Toscano","Bordallo","Murilo","Cabral","Galleti","França","Fagundes","Cândido","Roldão",
    "Camargo","Nóbrega","Serpa","Curi","Schiavon","Gusmão","Salles","Penna","Penido","Mazza",
    "Amado","Baltar","Capanema","Braz","Brazão","Pedrosa","Castelhano","Malta","Alvarenga","Junior",
    "Roque","Porto","Félix","Tôrres","Sabino","Brandão","Lacerda","Valença","Canci","Vergara",
    "Fraga","Braga","Naves","Macedo","Bernardino","Lourenço","Bicalho","Ferraz","Cerqueira","Torrado",
    "Faioli","Benedito","Deodato","Calmon","Vilela","Lira","Padilha","Sbaraini","Pedroni","Sobreira",
    "Vasques","Santos Filho","Mourão","Torrico","Pazin","Baldez","Garcez","Mizuno","Uehara","Andrada",
    "Coelho","Gaudêncio","Arcoverde","Américo","Borges","Zampieri","Catramby","Barone","Amâncio","Toledo",
    "Ratti","Scarpelli","Venturini","Belmonte","Sorrentino","Castiglione","Marangoni","Montes","Pierri","Ranzani",
    "Rossetti","Giordano","Zandoná","Germiniani","Ventura","Masiero","Bacelar","Castanho","Reznik","Couto",
    "Branquinho","Serpa","Frade","Catunda","Gimenes","Fayad","Scalabrini","Medrado","Torrente","Guerzoni",
    "Zacarias","Bragatto","Simões","Abreu","Galvão","Ramalhete","Perroni","Carvalhaes","Vasconcellos","Gonçalves",
    "Bedim","Mariante","Calsavara","Serrano","Taveira","Capanema","Azambuja","Bernardes","Portilho","Cangussu",
    "Belens","Fonseca","Vitral","Cangueiro","Viegas","Xisto","Pontes","Albuquerque","Barcellos","Sartori",
    "Quintanilha","Lemos","Venturoli","Cestari","Cichelero","Anhaia","Laporta","Mendonça","Gaspar","Fraiha",
    "Lavinas","Nolli","Guarnieri","Terto","Sardenberg","Guareschi","Zattar","Rivelli","Salles","Froes",
    "Cardin","Cursino","Cazagrande","Fagundes","Nobrega","Travessa","Rolim","Solano","Demetrio","Bonfim",
    "Valle","Bordallo","Cestaro","Vileti","Trindade","Garrido","Bellan","Damasceno","Linardi","Carrijo",
    "Zamora","Taveira","Pedrosa","Foronda","Magalhães","Prado","Menezes","Beltrame","Scherer","Cancio",
    "Carmo","Ravagnani","Ramalho","Vassalo","Funchal","Esmeraldo","Guaracy","Pontes","Curvelo","Vittorazzi",
    "Tagliari","Machado","Aragão","Costa","Sassaki","Mukai","Ishida","Nishimura","Yamamoto","Nakayama",
    "Tanaka","Watanabe","Kitano","Arakaki","Uehara","Shinzato","Nagata","Koga","Matsumoto","Sakata",
    "Paulucci","Matarazzo","Calabresi","Gianvecchio","Scarpin","Meneghini","Giannotti","Belfort","Lobato","Moretti",
    "Talarico","Scucuglia","Pagliarini","Sangiovani","Mazzilli","Bianchini","Costella","Montagnini","Campanella","Trevisani",
    "Vizzoni","Zancan","Cassol","Passamani","Almada","Zanchi","Ribolli","Guzzoni","Coiado","Beline",
    "Padoveze","Mantovani","Pinotti","Bertolini","Zaccaro","Saragiotto","Sturion","Zumpano","Durazzo","Barbieri",
    "Beux","Serafim","Cotrim","Piazza","Favoreto","Abrão","Sodré","Amato","Campideli","Baldin",
    "Mezzomo","Fumis","Corazza","Becher","Buzatti","Bertazzi","Frasson","Tessaro","Bellato","Domenes",
    "Albarello","Daronco","Dalcin","Barreto","Alcântara","Carriel","Miranda","Torres","Serradourada","Perecini",
    "Fraga","Gandini","Camurça","Bezerra","Alcoforado","Sabóia","Accioli","Coimbra","Camargos","Roriz",
    "Arruda","Severino","Ramiro","Alencar","Frota","Saba","Uchoa","Leal","Belo","Guerreiro",
    "Picanço","Benício","Arcoverde","Vasconcelos","Couto","Gazzo","Passarelli","Cassemiro","Ramos","Torrado",
    "Galindo","Pessanha","Bertoni","Rebouças","Galdino","Belém","Espínola","Ramaldes","Niero","Schiavini",
    "Valladares","Herkenhoff","Beltrão","Zanini","Gervásio","Murta","Alvim","Brittes","Ataíde","Calais",
    "Canedo","Lacerda","Faleiro","Vasques","Biazotto","Ribas","Ribas","Zagalo","Pina","Ornelas",
    "Martinho","Pessotti","Serafim","Braz","Guarino","Bicalho","Ferraz","Maleski","Cavallini","Ferreirinha",
    "Detoni","Betega","Borschiver","Klein","Bergmann","Lieberman","Weiss","Rosenfeld","Mizrahi","Stern",
    "Benvenutti","Schein","Weissmann","Prince","Rosenbaum","Goldstein","Kaufmann","Lustig","Feldman","Kattan",
    "Morel","Schubert","Pagotto","Silveirinha","Benfatti","Ciscato","Funchal","Gottardi","Valverde","Sperandio",
    "Dalbianco","Gonçalves Neto","Schafer","Altamir","Bardin","Venturoso","Scorsin","Canabarro","Pletz","Caminha",
    "Miziara","Cyrillo","Bravin","Caparroz","Ramos Filho","Matta","Maldonado","Righetto","Fiorin","Garcia Lopes",
    "Camposs","Artoni","Delgado","Galatti","Correchel","Brandini","Zorzi","Zamperlini","Frighetto","Pellicer",
    "Landim","Gandolfo","Rizzetto","Vissotto","Canez","Sampaio Filho","Flores","Delmondes","Rezende Filho","Najm",
    "Alfonsi","Pereira Leite","Covizzi","Ferronato","Triches","Zottis","Guidotti","Cabanellas","Bettiol","Cason",
    "Boff","Righetti","Angonese","Benatti","Fioravantti","Rebouças Filho","Leismann","Baricelli","Ferreirinha","Belluzo",
    "Zampolli","Mantana","Magnabosco","Calixto","Alcoba","Cavedon","Mattje","Tassoni","Luppe","Rigo",
    "Perondi","Girotti","Amarante","Frizon","Dalla Costa","Silvares","Carmello","Prigol","Comar","Nicolielo",
    "Teodorico","Tessitore","Albarez","Zamignani","Bocchi","Rodarte","Damiani","Maranhão","Garré","Menezes Filho",
    "Fortunato","Schiavon","Baldoino","Navarro","Botelho","Garbim","Bisi","Bianconi","Mamberti","Pazzini",
    "Vax","Coury","Veríssimo","Nardeli","Vechi","Renck","Ribamar","Damaceno","Ortegal","Garboggini",
    "Badin","Mazzafera","Toquetti","Tonietto","Graziani","Gai","Serrano Filho","Copelli","Pedriali","Ubaldo",
    "Valejos","Volpini","Bacarin","Vescovi","Munhoz","Escobar","Cardoso Filho","Amaral Neto","Manhães","Guedes",
    "Aragones","Baracho","Romanelli","Haddad","Maluf","Boulos","Caprini","Capelari","Nascibem","Cardarelli",
    "Prudêncio","Peccin","Mirabile","Pedroso","Guastelli","Graeff","Barretto","Garzoni","Sartini","Marciano",
    "Lazzarini","Giroldo","Boller","Ferracini","Artoni","Rovaris","Franzin","Bonadio","Fabiani","Cianflone",
    "Nolli","Sartor","Zani","Calheiros","Quaresma","Veridiano","Antas","Binda","Gorgulho","Medina",
    "Arrivabene","Iturri","Zednik","Possa","Batistela","Piovesan","Andrade Filho","Gonçal","Castilho","Bertoncello",
    "Calafatti","Loreto","Lorenzini","Svorcan","Micuza","Skowronski","Romanó","Beluzzo","Barlattani","Massucatti",
    "Stellet","Daltro","Euler","Kaefer","Maziero","Saad","Farah","Diniz","Hage","Saikali",
    "Werneck","Steinbruch","Herszkowicz","Bressan","Cassoli","Trevisol","Lorencini","Marçola","Lorenco","Mezadri",
    "Milaré","Righeto","Sobral","Imbriani","Rufino","Vieitas","Gusmão Filho","Saldanha","Verneck","Maffei",
    "Appel","Kleinert","Preuss","Kruger","Schmidt","Beckmann","Kremer","Hoffmann","Vogel","Steiner",
    "Bruns","Jaeger","Schramm","Hartmann","Schneider","Negrão","Takata","Yoshida","Kimura","Junqueira",
    "Manzoli","Bruschi","Canzian","Scudeler","De Pietri","Marini","Gaioto","Campanharo","Marson","Burani",
    "Gasques","Milanez","Bisognin","Dalben","Anselmo","Vido","Donatti","Sassá","Luchesi","Damin",
    "Boffoni","Ferracioli","Fagionato","Tartarotti","Casarin","Piaulino","Zatta","Vendramini","Vanzela","Beccaro",
    "Rosolem","Bagnara","Coltro","Bordignon","Ferronato","Magrin","Pallu","Mian","Rosar","Bertoldi",
    "Peres","Daltro Filho","Calabrez","Dalmaso","Bolognani","Rigoletto","Zagonel","Specian","Dalmolin","Modafferi",
    "Favaro","Giordani","Menegueti","Bellodi","Cagnin","Zavatti","Grandis","Pedruzzi","Tonon","Busatto",
    "Canalli","Baracat","Sabbag","Azar","Heneine","Gianordoli","Casali","Faracco","Farhat","Curee",
    "Guarezi","Fuscaldo","Bulhões","Marcondes","Ghiraldelli","Bergo","Tofoli","Mucelin","Busnello","Maseron",
    "Schiffler","Lovatto","Naufel","Perrone","Acatauassu","Bongiovani","Gonsalves","Todelo","Perrini","Marzola",
    "Ferrarini","Manfrin","Baleroni","Scarmagnani","Vanzetti","Riccitelli","Porcari","Brunhari","Melchior","Rabello"
]
;